"""add user_id to todos

Revision ID: 992af37702a0
Revises: 57f60fae060e
Create Date: 2026-02-19 14:28:28.263598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992af37702a0'
down_revision: Union[str, Sequence[str], None] = '57f60fae060e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    # ### end Alembic commands ###
